apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/hybrid-cloud-team/my-ecr-obs-2.git
    targetRevision: main
    path: obs/kibana/deploy   # ✅ 실제 존재

  destination:
    server: https://kubernetes.default.svc
    namespace: logging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
