apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: |
      elasticsearch=635014547592.dkr.ecr.ap-northeast-2.amazonaws.com/elasticsearch-s3
    argocd-image-updater.argoproj.io/elasticsearch.update-strategy: newest-build
    argocd-image-updater.argoproj.io/elasticsearch.allow-tags: regexp:^7\.17\.16$
spec:
  project: default

  source:
    repoURL: https://github.com/hybrid-cloud-team/my-ecr-obs-2.git
    targetRevision: main
    path: obs/elasticsearch/deploy

  destination:
    server: https://kubernetes.default.svc
    namespace: logging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
